ComposableFi/emulated-light-client

common/blockchain/Cargo.toml
common/blockchain/src/candidates.rs
common/blockchain/src/candidates/tests.rs
common/blockchain/src/manager.rs
common/blockchain/src/validators.rs

Rather than keeping state root in the chain manager, make it the
responsibility of the customer of the class.  After all, it’s the
customer who will also hold onto the Trie and thus have easy access
the state root.

blockchain: remove state root from chain manager

---

solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/lib.rs

We are having a mapping between connectionId to clientId ( connectionId is the key ) but it should be the other way round since we would query the connection using client.

change client to connection from connection to client

---

common/blockchain/src/candidates/tests.rs

Left over from previous commit.  Conversion to u128 in the match
statement is unnecessary.  Get rid of it and with that move the
conversion down to call to test_update.

blockchain: remove unnecessary conversion to u128 [tiny change]

---

solana/solana-ibc/programs/solana-ibc/Cargo.toml
solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/tests.rs

Change deliver function to take a single message rather than e vector
of messages.  If caller needs to handle multiple messages, which is
probably uncommon, they can batch Solana transactions.
With that change, handle errors better by actually returning them on
failure.

solana-ibc: accept just one message in deliver

---

common/sealable-trie/src/trie.rs
common/sealable-trie/src/trie/tests.rs
solana/solana-ibc/programs/solana-ibc/src/execution_context.rs

Fully optimised set and seal operation is still to be done.  For now
add the `set_and_seal` method to the Trie which removes just the most
trivial duplicate work but really serves more as a placeholder so that
clients can start using the method in anticipation of an optimised
version.

sealable-trie: add slightly optimised `set_and_seal` method

---

solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs
solana/solana-ibc/programs/solana-ibc/src/validation_context.rs

Issue: https://github.com/ComposableFi/emulated-light-client/issues/46

solana-ibc: serialise ConnectionEnd and ChannelEnd w/ borsh i/o serde

---

solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/lib.rs

Avoid unwraps by converting borsh errors into IBC errors which get
propagated up the call tree.

solana-ibc: better propagate errors

---

solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs

For the sake of relayer, remember sequence numbers of packet and
acknowledgement commitments in the private storage.
This isn’t strictly necessary since the data can be read from the
trie, but that requires iterator interface which isn’t yet
implemented.  For the time being, use sets in the private storage.

solana-ibc: remember sequence numbers of commitments in private storage

---

Cargo.toml
common/blockchain/src/manager.rs
common/sealable-trie/Cargo.toml
common/sealable-trie/src/bits.rs
common/stdx/src/lib.rs

1. Compiler is actually smart enough to figure out that unsigned
number + 1 is non-zero and optimises NonZeroU128::new(n + 1)
correctly.  Get rid of the unsafe block and new_unchecked call.
2. Use ascii crate’s AsciiChar when formatting the bits slice.  This
removes the need from converting slice of bytes into a str slice.
Instead, we get AsciiStr for free which can be converted to str.
3. Remove unused as_chunks_mut method from the stdx crate.

Reduce amount of unsafe code

---

common/lib/Cargo.toml
common/lib/src/hash.rs

When building for Solana use sol_sha256 syscall rather than sha2 crate
to calculate the digest.  The host function should be more efficient.

lib: support Solana in CryptoHash

---

common/blockchain/src/block.rs
common/blockchain/src/lib.rs
common/blockchain/src/manager.rs
common/blockchain/src/validators.rs

Add an Verifier trait rather than a verify method on a Signature.  The
purpose is to allow additional context to be provided when checking
signatures.  This is needed in Solana where signature checking
requires access to per-request data (specifically instructions native
program which is passed with the rest of accounts).

blockchain: add Verifier trait

---

Cargo.toml
solana/solana-ibc/programs/solana-ibc/Cargo.toml
solana/solana-ibc/programs/solana-ibc/src/ed25519.rs
solana/solana-ibc/programs/solana-ibc/src/lib.rs

Implement Ed25519 verification using Solana’s native program.  For now
the code is unused but will be needed for checking validator’s
signatures.  No signing code is implemented since that’s never done
on-chain.

solana-ibc: add Ed25519 support

---

common/blockchain/Cargo.toml
common/blockchain/src/block.rs
common/blockchain/src/manager.rs
solana/solana-ibc/programs/solana-ibc/Cargo.toml
solana/solana-ibc/programs/solana-ibc/src/error.rs
solana/solana-ibc/programs/solana-ibc/src/lib.rs

The module is tiny at the moment but with time more variants will be
added to the variant which would otherwise live in the lib.rs file
making it grow in size even more.

solana-ibc: introduce error module; move Error enum there

---

solana/solana-ibc/programs/solana-ibc/Cargo.toml
solana/solana-ibc/programs/solana-ibc/src/events.rs
solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs

Firstly, remove ibc_events_history from the storage.  The field only
ever grows which isn’t sustainable.  The contract has no use for the
field and off-chain customers should look at history of Solana logs
rather than looking at the field.
Secondly, encode the IBC event directly in an event struct rather than
first borsh serialising it and then emitting that.  Since emitting
causes another borsh serialisation this leads to somewhat awkward and
unnecessary double serialisation.
Lastly, use Solana logging directly rather than using Anchor’s logging
infrastructure.  Anchor really doesn’t give us much as far as I can
tell and having an enum with all possible events which is serialised
is just as if not more convenient.

solana-ibc: refactor events handling

---

common/blockchain/src/manager.rs

Add return values to distinguish a valid new signature and a valid
duplicate signature.  This is important to be able for the caller to
determine whether a new signature has indeed been introduced or
whether the signature submission can be ignored.

blockchain: extend return type of ChainManager::add_signature

---

solana/solana-ibc/programs/solana-ibc/src/execution_context.rs

The `msg` macro which solana uses for logging is not the same as `println` macro i feel. Some of the formatting which we used to do in `println` macro like 
```
let x = 5;
println!("{x}"); 
```
Doesnt seem to work in `msg` macro. When used the above with msg macro, the output is -> `{x}`. So we have to specify empty braces and then pass the arguments outside the quotes. So this PR fixes that.

change the string formatting in msg macro

---

.github/workflows/master.yml
common/lib/src/test_utils.rs
common/sealable-trie/src/trie/tests.rs

Limit stress tests to just five iterations when running on Miri.  This
makes them actually quite fast (faster than some regular tests) so
they can be added back to CI.
Furthermore, disable the slowest trie tests on Miri introducing their
smaller variants which run on Miri in reasonable time.  Largest
example is test_del which on my machine takes 144 seconds while
test_del_small takes 18.  To be fair I’d argue it’s still considerable
for a unit test but definitely much more reasonable.

Enable stress tests on Miri and shrink couple other tests

---

common/blockchain/Cargo.toml
common/blockchain/src/block.rs
common/blockchain/src/manager.rs
common/blockchain/src/validators.rs

So far signing schema was such that validators would sign
Borsh-selialised block.  This had two undesirable properties:
1. If the same validator signed blocks for two different blockchains,
the could be accused of double signing since there was no way to
distinguish that signatures belong to two different chains.
2. To prove misbehaviour, full block had to be transmitted.  This
becomes a bit of an issue for blocks which are final in an epoch
since those include new epoch which may be couple KB in size.
This commit introduces a Fingerprint which is what validators
sign. The fingerprint is concatenation of a) genesis block hash, b)
block height as little endian¹ and c) block hash.  This addresses the
above concerns:
1. Since fingerprint includes chain’s genesis hash (which uniquely …

blockchain: introduce Fingerprint and change singing schema

---

common/sealable-trie/src/bits.rs
common/sealable-trie/src/bits/ext_key.rs
common/sealable-trie/src/nodes.rs
common/sealable-trie/src/nodes/stress_tests.rs
common/sealable-trie/src/nodes/tests.rs
common/sealable-trie/src/proof.rs
common/sealable-trie/src/proof/serialisation.rs
common/sealable-trie/src/trie.rs
common/sealable-trie/src/trie/del.rs
common/sealable-trie/src/trie/seal.rs
common/sealable-trie/src/trie/set.rs

Introduce bits::ExtKey type which is a wrapper around bits::Slice with
bounded length.  ExtKey cannot be empty and its underlying bytes
cannot exceed 34 bytes.  The type corresponds to a key stored in an
Extension node.
Having the type simplifies raw node encoding since we now don’t need
to worry about cases where empty or long key is passed as extension
key; we can get rid of Slice::write_into and hash_extension_slow_path.

sealable-trie: introduce bits::ExtKey type

---

solana/solana-ibc/programs/solana-ibc/src/chain.rs
solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/host.rs
solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs
solana/solana-ibc/programs/solana-ibc/src/validation_context.rs

Properly implement host_height method to return Solana’s block height
(i.e. slot number) rather than using data from account.  The existing
implementation was just a quick hack to get some data going but is by
no means correct.

solana-ibc: implement host_height method

---

solana/solana-ibc/programs/solana-ibc/src/client_state.rs
solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs
solana/solana-ibc/programs/solana-ibc/src/validation_context.rs

Simplify code by removing conversion between ibc::Height and (u64,
u64) tuple when storing heights in private IBC storage.  The two types
are morally equivalent and using the tuple doesn’t offer us any
benefits.

solana-ibc: use ibc::Height for storing height in private storage

---

solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs

Some of them were only ever set.  connection_id_set was never even
changed.  The identifier sets can be determined from other fields
so if off-chain code needs that information it can easily get it.

solana-ibc: remove unused storage fields

---

solana/solana-ibc/programs/solana-ibc/src/transfer/mod.rs

When possible prefer string::from_utf8 over String::from_utf8
Ref: https://doc.rust-lang.org/beta/std/str/fn.from_utf8.html

transfer: unnecessary allocations

---

solana/solana-ibc/programs/solana-ibc/src/client_state.rs
solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs
solana/solana-ibc/programs/solana-ibc/src/validation_context.rs

Rather than using untyped `Vec<u8>` for places where serialised
objects are kept in storage, introduce a `Serialised<T>` wrapper which
allows typing the stored object.

solana-ibc: introduce Serialised wrapper in storage

---

solana/solana-ibc/programs/solana-ibc/src/client_state.rs

AnyConsensusState already has derive_more::TryInto derive; add it to
AnyClientState as well.

solana-ibc: add derive_more::TryInto to AnyClientState  [trivial]

---

common/lib/src/hash.rs
solana/solana-ibc/programs/solana-ibc/src/client_state.rs
solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs
solana/solana-ibc/programs/solana-ibc/src/trie_key.rs
solana/solana-ibc/programs/solana-ibc/src/validation_context.rs

IBC client ids have `<client-type>-<counter>` format where counter is
a global sequential number.  Take advantage of that by converting
client ids into u32 including just the counter.
Since we’re effectively ignoring the client-type part of the id, keep
counter → client id map in private storage and use it to verify that
id we were given is the one we know about.
Furthermore, rather than storing client information in a map keep it
in a vector which is more compact and faster to index.  At the same
time, keep just a single vector for all per-client data rather than
having separate maps for each piece of information.

solana-ibc: map IBC client ids into u32 and refactor client state storage

---

solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs
solana/solana-ibc/programs/solana-ibc/src/storage/ids.rs
solana/solana-ibc/programs/solana-ibc/src/storage/trie_key.rs
solana/solana-ibc/programs/solana-ibc/src/validation_context.rs

Move trie_key inside of storage module and add storage::ids module
with ClientIndex type and other identifier related code.  The new
module will house other code related to converting IBC identifiers
into compact internal ones.

solana-ibc: refactor module structure

---

solana/solana-ibc/programs/solana-ibc/src/execution_context.rs

`msg!("{}", message)` includes a `format!` call which needs to
allocate a new string which is then logged.  `message` is already
a string thus this formatting step is wasteful.  Use single-argument
invocation of `msg!` which avoids the formatting step and logs the
string argument directly.

solana-ibc: avoid string copy when calling msg  [trivial]

---

solana/solana-ibc/programs/solana-ibc/src/client_state.rs
solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs
solana/solana-ibc/programs/solana-ibc/src/validation_context.rs

Firstly, and most importantly, add a missing client_id check in
PrivateStorage::client_mut method.  When getting an existing client we
must check that the client id given as argument matches the one stored
in the ClientStore.  PrivateStorage::client performed that check alas,
PrivateStorage::client_mut lacked it.  Add it as required.
Secondly, introduce ClientRef and ClientMut reference types which
replace previously used pairs.  Those type clarify some of the code by
naming the index field and simplify other code by removing the need
for `.1` to get the reference.

solana-ibc: fix lack of client id checking and add client references

---

common/sealable-trie/src/trie/tests.rs
solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs
solana/solana-ibc/programs/solana-ibc/src/storage/ids.rs
solana/solana-ibc/programs/solana-ibc/src/storage/trie_key.rs
solana/solana-ibc/programs/solana-ibc/src/validation_context.rs

IBC connections identifiers are in the form `connection-<number>` and
use sequential numbering.  Take advantage of that by introducing
ConnectionIdx type which only holds the number and storing connection
information in a vector rather than a map.  This is analogous to
change already made for clients.

solana-ibc: introduce ConnectionIdx type for connection identification

---

common/lib/src/hash.rs
solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs
solana/solana-ibc/programs/solana-ibc/src/storage/trie_key.rs

As we parse client ids we strip out the client type.  This means
that ‘foo-42’ and ‘bar-42’ are internally represented as 42.  To
avoid confusion, we keep the client ids in private storage and
whenever we index client data by the number we check that the
full client id matches.
However, that information isn’t currently available in provable
storage (i.e. it’s not verifiable by light clients).
Change hash we’re storing under client state path to include the
client id.  This way, light clients will be able to verify that
indexes they’re extracting from the client id match the client id
they are given.

solana-ibc: store proof of client id together with client state

---

solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs
solana/solana-ibc/programs/solana-ibc/src/storage/ids.rs
solana/solana-ibc/programs/solana-ibc/src/storage/trie_key.rs
solana/solana-ibc/programs/solana-ibc/src/validation_context.rs

Analogous to ConnectionIdx for connection identifiers, introduce
ChannelIdx type which represents a channel identifier.  It takes
advantage of our channels using `channel-<number>` format and
allows to store channel identifiers in more efficient way.

solana-ibc: introduce ChannelIdx type for channel identification

---

common/sealable-trie/src/bits.rs
common/sealable-trie/src/trie/del.rs

In addition to providing fallible conversion from bit slice to a Vec,
reword Owned::concat method so it works on slices.  All of those
changes as well as Default implementation for both types will be
needed in upcoming change for subtrie iteration.

solana-ibc: introduce TryFrom conversion into Vec for Slice and Owned

---

solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs

Many of the modules are private which makes them unable to use them
when the project is imported in the relayer. There are some interfaces
which are needed to be imported from this crate. So this PR makes the
required modules public.
Maybe we can split them into seperate crates in the future so that
they can be imported as needed.

solana-ibc: make some modules public

---

solana/solana-ibc/programs/solana-ibc/src/storage/ids.rs

Making them public so that the `channel_id` and `port_id` can be accessed. 
Should we add getter method or making them public is fine?

make attributes of portChanelPk struct public

---

solana/solana-ibc/programs/solana-ibc/src/storage/ids.rs
solana/solana-ibc/programs/solana-ibc/src/storage/trie_key.rs

Restrict port identifier to be 12 alphanumeric characters.  With that
restriction it’s now possible to decode the port using base64 encoding
to get 9 bytes.  Those bytes can then serve as an internal port
identifier used with the trie and maps in private storage.

solana-ibc: restrict port identifier and use more compact representation

---

solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/storage/trie_key.rs

Documentation of the for_client_state method disagreed with the
code. Update it to reflect reality.  While at it update what’s hashed
to match borsh serialisation.

solana-ibc: update for_client_state documentation

---

solana/solana-ibc/programs/solana-ibc/src/storage/trie_key.rs

Instead of using a Vec to store the TrieKey, limit the maximum length
of the TrieKey and store the value within the structure itself.  Since
we know all possible keys and each key component is fixed-size, we can
easily deduce the longest possible key.  Turns out it’s 22.  That’s
a reasonable size of a buffer to keep within the TrieKey instead of
doing a heap allocation with a Vec.

solana-ibc: limit the maximum length of the TrieKey; use on-stack buffer

---

README.md

We were running the local validator because we wanted increased
compute units (> 300k).  Since then we have added a new instruction
in tests to increase the compute units to 1M before each transaction.
This way we wouldn’t need to run a local validator.

solana-ibc: updated readme to remove running local validator

---

solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/mocks.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs
solana/solana-ibc/programs/solana-ibc/src/tests.rs

Storing packets on chain would easily pile up since they are just
added and not removed.  The previous delivered packets aren’t needed
in the smart contract so there is no point in storing them there.  The
packets are required by the relayer which can be fetched by querying
the logs.

solana-ibc: remove packets storage

---

common/blockchain/src/candidates.rs
common/blockchain/src/candidates/tests.rs
common/lib/src/lib.rs
common/lib/src/u3.rs
common/sealable-trie/src/bits.rs
common/sealable-trie/src/bits/ext_key.rs
common/sealable-trie/src/nodes/stress_tests.rs
common/sealable-trie/src/nodes/tests.rs
common/sealable-trie/src/proof/serialisation.rs

Encode in type that slice’s offset can be at most 7 by introducing
a new lib::u3::U3 type and use it for storing the offset.  As the name
implies, the type is written to hold 3-bit unsigned integers, or in
other words numbers from 0 to 7.
This allows offset check to be removed from Slice and Owned
constructors and since everything is encapsulated the users of the
types need only minimal adjustments.
This actually fixes a bug in Owned::bit where the offset argument
wasn’t validated.  Since the only place which called that function
used offset taken from another slice this never created actual issue
but nonetheless the API is now tighter.

sealable-trie: introduce U3 type and use it for offset

---

solana/solana-ibc/programs/solana-ibc/src/ibc.rs
solana/solana-ibc/programs/solana-ibc/src/tests.rs

The timestamp default to `None` while setting up mock headers in the tests. Since they are not set ( `None` ), it fails while comparing the current timestamp. So using a value instead would solve it. The value has to be less than the current timestamp.

solana-ibc: use a proper timestamp in mock headers

---

common/lib/src/u3.rs
common/sealable-trie/src/bits.rs
common/sealable-trie/src/bits/concat.rs
common/sealable-trie/src/bits/ext_key.rs
common/sealable-trie/src/trie/del.rs

Add Owned::extend method which allows appending slices to the owned slice.
Do this through a generic concat::Concat trait and refactor other
concatenating methods to use a unified interface.  Specifically, this
removes unshift and push in favour of more flexible concat and a new
extend method.  Hopefully `Owned::concat(true, slice)` is more
descriptive than `Owned::unshift(true, slice)`.
With the new unified interfaces also comes more uniform error
handling.  Introduce concat::Error, concat::MisalignedSlice and
concat::SliceTooLong errors which are now consistently returned when
concatenation fails.  This covers length checking better and
eliminates panics if length of a concatenated slice is too large.
Furthermore, add Owned::truncate method which allows shortening of the
slice to …

solana-ibc: introduce Owned::extend and Owned::truncate

---

solana/solana-ibc/programs/solana-ibc/src/client_state.rs
solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/mocks.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs
solana/solana-ibc/programs/solana-ibc/src/transfer/impls.rs
solana/solana-ibc/programs/solana-ibc/src/transfer/mod.rs
solana/solana-ibc/programs/solana-ibc/src/validation_context.rs

Tighten lifetimes in entrypoint functions so that we can get rid of
third lifetime argument in IbcStorage structure.  With that also
replace `accounts` field from being a vector into being a slice
reference which avoids allocation.

solana-ibc: simplify storage lifetimes

---

common/blockchain/src/block.rs
common/blockchain/src/height.rs
common/blockchain/src/manager.rs
solana/solana-ibc/programs/solana-ibc/src/events.rs
solana/solana-ibc/programs/solana-ibc/src/host.rs

Use NonZeroU64 for the host_timestamp field of a block.  1970 was half
a century age and any timestamps the blockchain will work are way past
that so there’s no need to handle zero timestamp.

blockchain: change timestamp to be non-zero

---

common/sealable-trie/src/bits/ext_key.rs
common/sealable-trie/src/nodes.rs
common/sealable-trie/src/nodes/stress_tests.rs
common/sealable-trie/src/nodes/tests.rs
common/sealable-trie/src/proof.rs
common/sealable-trie/src/proof/serialisation.rs
common/sealable-trie/src/trie.rs
common/sealable-trie/src/trie/del.rs
common/sealable-trie/src/trie/seal.rs
common/sealable-trie/src/trie/set.rs
common/sealable-trie/src/trie/tests.rs

Due to the nature of sealable trie, storing values at a prefix of an
existing key isn’t supported.  To understand why, consider the
following sequence of operations:
* set 0000 → foo
* set 0001 → bar
* seal 0000
* seal 0001
* set 000 → baz
After the second seal operation, node 000 is sealed as well.  This is
what makes sealing a worthwhile pursue allowing us to prune subtries
as the leafs are sealed.
But if 000 is sealed than setting 000 → baz cannot happen even though
the key wasn’t explicitly sealed.  However, if that operation was
performed earlier, it would succeed with the key being able to be
modified.
Similarly, it’s already been codded that sealing a key seals the
entire subtrie.
All of this is somewhat surprising and inconsistent.  To avoid all
that confusion, simply prohibit …

sealable-trie: prohibit storing values at key prefixes

---

Cargo.toml

Rather than pointing at private repositories, point at commits within
upstream repositories for all the patched crates.

Crate.toml: prefer upstream patches

---

common/trie-ids/Cargo.toml
common/trie-ids/src/lib.rs
common/trie-ids/src/trie_key.rs
solana/solana-ibc/programs/solana-ibc/src/tests.rs

Since we can fetch from trie using prefix of the key which is used to
fetch all the packet commitments, acks and recv, we need to make `Tag`
enum and the methods used to create new key as public so that we can
create sub trie keys.

trie-ids: make `Tag` and related methods and traits public to create sub trie keys

---

.github/workflows/master.yml
Anchor.toml
Cargo.toml
solana/solana-ibc/programs/solana-ibc/src/lib.rs

Anchor doesn’t like when array sizes aren’t integer literals.  This is
dumb but there’s not much we can do other than change argument type
from a somewhat descriptive `[u8; ed25519::Signature::LENGTH]` to
a somewhat cryptic `[u8; 64]`.  This fixes `anchor build` run.
With that, add Anchor Build to CI so it’s tested on each PR.  While
doing that, rearrange CI jobs a little so that their run time is more
balanced.

solana-ibc: fix `anchor build` and add it to CI

---

solana/solana-ibc/programs/solana-ibc/src/client_state.rs
solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs
solana/solana-ibc/programs/solana-ibc/src/validation_context.rs

Introduce storage::ClientConsensusState type which stores processed
timestamp, processed height and the consensus state and use it rather
than having three separate maps for each of those elements.
This is built on observation that the three elements are always set
and deleted together.
Having fewer maps reduces memory usage since the same tree structure
doesn’t need to be repeated three times.

solana-ibc: combine processed time, height and consensus state

---

solana/solana-ibc/programs/solana-ibc/Cargo.toml
solana/solana-ibc/programs/solana-ibc/src/chain.rs
solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/tests.rs

Most notably, add chain initialisation to the Anchor test. During chain initialization, we also initialize all the storage accounts ( private storage, trie and chain data ) since its only called once in the lifetime of the program. Hence the use `inif_if_needed` for storage accounts serve no purpose thus save us some from `re-initialization` attacks. While at
it, change some logging in the test so it’s easier to read the logs.

solana-ibc: initialise chain in Anchor test

---

solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/mocks.rs
solana/solana-ibc/programs/solana-ibc/src/no-mocks.rs
solana/solana-ibc/programs/solana-ibc/src/tests.rs
solana/solana-ibc/programs/solana-ibc/src/transfer/impls.rs

Split out mint and escrow initialisation out of mock_deliver and into
mock_init_escrow instruction.  This is done so that the former has
fewer things to initialise and we don’t run into stack or heap memory
issues.
Also, sneak in addition of chain field to the MockDeliver to
demonstrate that this indeed achieves desired result.  Previously,
adding the field into the struct would lead to stack frame overflow.

solana-ibc: introduce separate mock_init_escrow instruction

---

solana/solana-ibc/programs/solana-ibc/src/chain.rs
solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/host.rs
solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/mocks.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs
solana/solana-ibc/programs/solana-ibc/src/validation_context.rs

Rather than using Solana timestamp and slot number for the host
timestamp and height use that information from guest blockchain’s head
block.  This is because in terms of IBC, the ‘host’ is the guest
blockchain since IBC communication happens between counterparty and
the guest blockchain and not directly with Solana.

solana-ibc: implement host_timestamp and host_height in terms of guest chain

---

.github/workflows/master.yml
Anchor.toml
Cargo.toml
common/blockchain/Cargo.toml
common/blockchain/build.rs
common/blockchain/proto/guest.proto
common/blockchain/src/lib.rs
common/blockchain/src/proto.rs
solana/solana-ibc/programs/solana-ibc/src/chain.rs
solana/solana-ibc/programs/solana-ibc/src/consensus_state.rs
solana/solana-ibc/programs/solana-ibc/src/error.rs
solana/solana-ibc/programs/solana-ibc/src/validation_context.rs

Define ConsensusState type together with protocol message and
implement the host_consensus_state method to return consensus state of
the guest blockchain at head height.  Getting consensus state of past
blocks isn’t supported at this moment and is still left to be done.

solana-ibc: implement guest blockchain’s consensus state

---

solana/solana-ibc/programs/solana-ibc/src/error.rs
solana/solana-ibc/programs/solana-ibc/src/ibc.rs
solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/tests.rs

Currently send_packet takes Packet as an argument.  This means that
caller has to know not only port and channel identifiers on our side
but also provide counterparty information and sequence number.  This,
however, makes no sense.
For counterparty information, it makes no sense because then we fetch
that information ourselves to figure out if it’s correct.  How about,
we just populate that information ourselves instead?
For sequence number this is actually a bug since it causes competing
send packet requests to clash.  If next squence number is 42 and two
users want to send a packet, only one of them will be accepted.
Again, instead of requiring user to send that information, fill it
ourselves.
Change the prototype of send_packet method such that it doesn’t take
counterparty information …

solana-ibc: remove dependent arguments from send_packet method

---

solana/solana-ibc/programs/solana-ibc/Cargo.toml
solana/solana-ibc/programs/solana-ibc/src/storage.rs

Due to error in a way bit was checked in a bitmap, SequenceTripple
would always return None for Recv and Ack sequences.  Fix that.

solana-ibc: fix bug in SequenceTripple returning None for Recv and Ack

---

solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs

When computing trie key for paths which include client id, we’re
stripping out the client type part of the id.  So keys to states of
clients ‘foo-0’ and ‘bar-0’ are the same.
To make sure that someone doesn’t produce a malicious proof which uses
wrong client type, (non-)membership verification algorithm must be
able to check the client id.  Make that possible by mixing in the
client id into the hash stored in the trie.
This way, if the path includes client id, the verification can
calculate the hash from value and client id and check if that was
stored in the trie.

solana-ibc: mix client id into trie values whose key depends on client

---

common/trie-ids/Cargo.toml
common/trie-ids/src/lib.rs
common/trie-ids/src/path_info.rs
common/trie-ids/src/trie_key.rs
solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs
solana/solana-ibc/programs/solana-ibc/src/validation_context.rs

Client state implementation deals with IBC’s Path type (which is an
enum of all possible paths) rather than concrete path types.  It
therefore needs code for converting that enum into TrieKey.  Introduce
it in the form of a PathInfo type.

trie-ids: introduce PathInfo structure holding info of parsed IBC path

---

common/sealable-trie/src/bits.rs
common/sealable-trie/src/bits/concat.rs
common/sealable-trie/src/trie/iter.rs

Using generics for extend implementation may be cool but it made the
code overly complex.  Simplify the bits::concat::Concat trait to
handle concatenation with creation of a new Owned object, replace
Owned::extend method by implementation which takes slice as suffix
parameter and add Owned::push_back for the case of appending a single
bit to the Owned slice.

sealable-trie: simplify extend implementation

---

solana/solana-ibc/programs/solana-ibc/Cargo.toml
solana/solana-ibc/programs/solana-ibc/src/storage.rs

Since zero is never stored under the next sequence path, it can be
used as a niche value for encoding `None` variant.  This simplifies
the encoding and code slightly.

solana-ibc: simplify SequenceTriple encoding

---

solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/validation_context.rs

Replacing explicit `Ok(())` with the `Result` provided by the methods.

solana-ibc: remove unneccesary Ok in validation and execution context

---

solana/solana-ibc/programs/solana-ibc/src/storage.rs
solana/solana-ibc/programs/solana-ibc/src/transfer/impls.rs

Since we are sending a struct of accounts with optional fields, there might be chances of not sending some accounts which are important. And also we check if the accounts which are PDAs are derived with right seed or not.

added validation for transfer methods

---

Cargo.lock
Cargo.toml
common/blockchain/Cargo.toml
common/blockchain/src/ibc_state/consensus.rs
common/blockchain/src/proto.rs
solana/solana-ibc/programs/solana-ibc/src/consensus_state.rs

Rather than manually implementing ConsensusState for AnyConsensusState
(which is just boilerplate dispatch code) use a derive to do that for
us.  Unfortunately, we cannot do the same with ClientState because of
<https://github.com/cosmos/ibc-rs/issues/910>.

solana-ibc: use ConsensusState derive

---

Cargo.lock
Cargo.toml
solana/solana-ibc/programs/solana-ibc/Cargo.toml
solana/solana-ibc/programs/solana-ibc/src/client_state.rs
solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs
solana/solana-ibc/programs/solana-ibc/src/storage/map.rs

In attempt to reduce memory usage and cost of serialising and
deserialising accounts, replace usage of BTreeMap with LinearMap which
is a vector-backed map.
Operations on the map have linear complexity, but since we’re not
doing many of them per instruction, chances are that time saved by not
having to build a tree structure when deserialising will make up for
that.
In fact, for small maps—which is what we’re having—it may be faster
regardless.  In anchor_test_deliver some of the instructions spend
fewer compute units while others use more so this would need further
investigation.

solana-ibc: use vector-backed maps rather than BTreeMap

---

solana/solana-ibc/programs/solana-ibc/Cargo.toml
solana/solana-ibc/programs/solana-ibc/src/allocator.rs
solana/solana-ibc/programs/solana-ibc/src/lib.rs

Default Solana allocator doesn’t support non-default heap sizes and
assumes heap is always 32 KiB.  Furthermore, since it’s just a naive
bump allocator it never deallocates.
Add custom allocator which handles heaps of different sizes and
attempts to deallocate memory at least in some situations.

solana-ibc: add custom allocator

---

solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/mocks.rs
solana/solana-ibc/programs/solana-ibc/src/no-mocks.rs
solana/solana-ibc/programs/solana-ibc/src/tests.rs
solana/solana-ibc/programs/solana-ibc/src/transfer/impls.rs

We were having a `init` methods where we were creating escrow accounts, but those escrow accounts were being created for wrapped tokens which were wrong. Since only native tokens are escrowed, they should be created for native token mint which will happen in the `send_transfer` method. Made the tests end to end where we escrow, mint, burn and then unescrow the same tokens.
Removed `mock_init_escrow` method and removed `escrow_account` from the init methods as well.
Renamed `init_escrow` to `init_mint`, since it would be called for initializing the wrapped token mint.
Shuffled the tests cases so that they are in proper order.
I observed that ibc uses `channel_id_on_b` for deriving escrow accounts when receiving packet and `channel_id_on_a` when sending a packet. So this would mean that …

solana-ibc: end to end tests and remove redunadancies

---

package.json
yarn.lock

Update start-server-and-test to 2.x which results in a newer axios indirect dependency which addresses vulnerability with the package:
> An issue discovered in Axios 0.8.1 through 1.5.1 inadvertently
> reveals the confidential XSRF-TOKEN stored in cookies by including
> it in the HTTP header X-XSRF-TOKEN for every request made to any
> host allowing attackers to view sensitive information.

yarn: update start-server-and-test dependency to bump axios

---

common/blockchain/build.rs
common/blockchain/src/ibc_state.rs
common/blockchain/src/ibc_state/consensus.rs
common/blockchain/src/proto.rs
common/lib/src/hash.rs
solana/solana-ibc/programs/solana-ibc/src/consensus_state.rs

Add proto::impl_proto macro which implements conversion from a raw
protocol buffer type to Any type and ibc_state::any_convert macro
which implements conversion between Rust message type and Any type.
For now, use them with ConsensusState.  In the future they will also
be used for ClientState.

blockchain: introduce helper impl_proto and any_convert macros

---

solana/restaking/README.md
solana/restaking/programs/restaking/src/lib.rs
solana/restaking/programs/restaking/src/token.rs
solana/restaking/programs/restaking/src/validation.rs
solana/restaking/tests/helper.ts
solana/restaking/tests/restaking.ts
solana/solana-ibc/programs/solana-ibc/src/lib.rs

Before the guest chain is initialized ( Bridge is launched ), users can stake their assets without choosing the validator since the validators don't exist yet. The staked tokens get locked in the vault and then when the bridge is launched, the users can set the stake on validator through the following options
- Choose a validator randomly
- Choose a validator from the list of top 10 validators chosen by us
- Choose a particular validator.
Also added `update_guest_chain_initialization` which would make the `is_guest_chain_initialized` as `true`.
The update methods are made seperate to isolate them such that one update doesn't fuck up the others.
Also fixed vulnerabilities from the audit.
1. The `Initialize` instruction can be called multiple times due to the use of `init_if_needed`, …

restaking: depositing before guest chain is initialized and fix vulnerabilites

---

Cargo.lock
common/blockchain/src/ibc_state/proof.rs

The `stdx::split_at` method has been changed in commit 8c74a55:
‘write-account: add Solana program for writing data into an account’
by adding type generic argument.  Update call site to reflect that.
This fixes a build failure which wasn’t caught because CI on the
offending commit wasn’t rerun between when the pull request was
initially made and when it was merged much later.

added generic argument in split_at method

---

solana/allocator/src/lib.rs
solana/allocator/src/ptr.rs
solana/allocator/src/tests.rs

Use pointer arithmetic with strict provenance to make Miri happy and
better test the allocator.  Strict provenance pointer methods are
unstable so copy what we need.

solana-allocator: use strict pointer provenance

---

solana/allocator/src/lib.rs
solana/allocator/src/ptr.rs
solana/allocator/src/tests.rs

This should have been part of previous commit really.  Sorry about the noise.

solana-allocator: simplify pointer arithmetic functions

---

.github/workflows/master.yml
Cargo.lock
Cargo.toml
common/blockchain/Cargo.toml
solana/ed25519/Cargo.toml
solana/ed25519/src/lib.rs
solana/restaking/programs/restaking/Cargo.toml
solana/solana-ibc/programs/solana-ibc/Cargo.toml
solana/solana-ibc/programs/solana-ibc/src/chain.rs
solana/solana-ibc/programs/solana-ibc/src/lib.rs

This is mostly because we are going to be patching ibc-rs to support
Solana signature verefication and to avoid circular dependencies we
need the ED25519 code in a separate crate that solana-ibc and ibc-rs
can both depend on.

solana-ed25519: move ED25519 Solana verification code into a new crate

---

Cargo.lock
solana/allocator/Cargo.toml
solana/allocator/src/lib.rs
solana/allocator/src/tests.rs
solana/solana-ibc/programs/solana-ibc/src/allocator.rs

Add support to reserve global state in the allocator.  This is to work
around Solana’s limitation of not allowing mutable statics.
With this feature, user can declare `BumpAllocator<T>` as the global
allocator and later use `BumpAllocator::global()` to get access to
`T`.

solana-allocator: add support for global state

---

.github/workflows/master.yml

Upgrade actions/cache, actions/checkout, actions/setup-node and
arduino/setup-protoc GitHub Actions to their respective latest
versions.  This is motivated by them updating their Node
dependency. It addresses the following warning:
> Node.js 16 actions are deprecated.  Please update the following
> actions to use Node.js 20: ….  For more information see:
> https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

github: upgrade CI actions

---

Cargo.lock
Cargo.toml
solana/ed25519/src/lib.rs
solana/solana-ibc/programs/solana-ibc/Cargo.toml
solana/solana-ibc/programs/solana-ibc/src/allocator.rs
solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/tests.rs

Take advantage of the support for global state in the allocator and
use it for the verifier state.  We’re using that state in patched
Tendermint client implementation to verify signatures there.
At the moment, because of the limitations of Solana we can verify less
than 10 signatures, but this change at least demonstrates the approach
we can take to have Tendermint client state updates implemented.

solana-ibc: use Solana ed25519 verifier for Tendermint client state

---

solana/write-account/src/lib.rs

Since the Write account needs to be a PDA, add support for creating
and resizing it as necessary.  We’re potentially missing Truncate and
Free instructions but we can live without them for the time being.
Furthermore, remove the Copy instruction.  We don’t use it currently
and having support for it while details of creation and resizing of
the account aren’t yet established create unnecessary maintenance
burden.

write-account: add support for creating and resizing the Write account

---

Cargo.lock
Cargo.toml
solana-test.sh
solana/solana-ibc/programs/solana-ibc/Cargo.toml
solana/solana-ibc/programs/solana-ibc/src/allocator.rs
solana/solana-ibc/programs/solana-ibc/src/ix_data_account.rs
solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/tests.rs

Introduce a mechanism by which clients of Solana IBC can store
instruction data inside of an account and then instruct Solana IBC to
read instruction data from said account rather than the Solana
transaction.
This is necessary because Solana limits transactions to roughly 1.2 kB
which includes full transaction including list of accounts, all the
instructions etc.  The end result is that some of the Solana IBC
instructions simply don’t fit.
Co-authored-by: Dhruv D Jain <dhruv@iamsizzling.com>

solana-ibc: support reading instruction data from account

---

common/blockchain/src/manager.rs
solana/solana-ibc/programs/solana-ibc/src/chain.rs
validator/src/utils.rs
validator/src/validator.rs

Checks and signs pending block if present before it listens to the events since until the pending block is signed, no new block event would be emitted.

validator: sign pending blocks

---

solana/solana-ibc/programs/solana-ibc/src/lib.rs

With the switch to custom entrypoint we also need to provide custom
panic handler.  Without it deploying the contract fails with the
following:
> Error: ELF error: ELF error: Unresolved symbol (custom_panic) at
> instruction #265306 (ELF file offset 0x2061e8)
>
> There was a problem deploying: Output { status:
> ExitStatus(unix_wait_status(256)), stdout: "", stderr: "" }.

solana-ibc: define missing custom_panic handler

---

Cargo.lock
Cargo.toml
solana/ed25519/Cargo.toml
solana/ed25519/src/lib.rs

Since solana uses base58 to display public keys, its better to use the same.

solana-ibc: display pubkey using base58 instead of base64

---

Cargo.lock
common/lib/Cargo.toml
common/lib/src/hash.rs
solana/ed25519/Cargo.toml
solana/solana-ibc/programs/solana-ibc/Cargo.toml
solana/trie/Cargo.toml

lib crate conditionally includes solana-program dependency if it’s built for Solana.  This allows using Solana-provided host functions for calculating the hash without caller having to care about the details.
However, the issue is that Cargo doesn’t always take target_os into consideration when resolving dependencies.  To be perfectly honest I’m not completely sure of the exact mechanics but the way the code is written now, when working with this crate in another project I’m getting the following failures:
error: failed to select a version for `curve25519-dalek`.
... required by package `solana-program v1.17.7`
versions that meet the requirements `^3.2.1` are: 3.2.1
previously selected package `curve25519-dalek v3.0.0`
... which satisfies dependency `curve25519-dalek = "^3"` of package …

lib: guard Solana support by `solana-program` feature

---

Cargo.lock
Cargo.toml
common/cf-guest/src/client_impls.rs
common/trie-ids/src/path_info.rs
solana/solana-ibc/programs/solana-ibc/Cargo.toml
solana/solana-ibc/programs/solana-ibc/src/allocator.rs
solana/solana-ibc/programs/solana-ibc/src/client_state.rs
solana/solana-ibc/programs/solana-ibc/src/client_state/impls.rs
solana/solana-ibc/programs/solana-ibc/src/consensus_state.rs
solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/ibc.rs
solana/solana-ibc/programs/solana-ibc/src/validation_context.rs

Upstream ibc-rs now supports custom signature verifier for Tendermint light client.  While version with the support hasn’t been released yet, it’s still better to use upstream code rather than using our own fork.
Apart from not maintaining a fork, this has additional benefit of providing much cleaner interface for accessing global state solana-ibc uses.

solana-ibc: update ibc-rs to upstream version

---

solana/restaking/README.md
solana/restaking/programs/restaking/src/constants.rs
solana/restaking/programs/restaking/src/lib.rs
solana/restaking/programs/restaking/src/token.rs
solana/restaking/tests/helper.ts
solana/restaking/tests/instructions.ts
solana/restaking/tests/restaking.ts
solana/solana-ibc/programs/solana-ibc/src/tests.rs

Added 7 days of unbonding period to withdrawals. User has to request for withdrawal where their receipt token is transferred to escrow until the unbonding period is over. But during that period, user has an option to cancel the withdrawal request and get back their receipt token. Once the unbonding period is over, the `withdraw` method can be called to perform the withdrawal.

restaking: added unbonding period to restaking

---

common/guestchain/src/candidates/tests.rs
common/guestchain/src/config.rs
common/guestchain/src/manager.rs
solana/solana-ibc/programs/solana-ibc/src/tests.rs

Block generation is driven by changes to the state and to the set of validators.  As a consequence, it is theoretically possible for a new block to not be produced for a very long time.  Since blocks carry time information this means that clients may lack time information necessary to handle time-based events such as timeouts.
Add option for setting maximum block age after which a new block can be generated even if old block doesn’t change state nor finishes epoch.

guestchain: add option for generating blocks if head is too old

---

common/cf-guest/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/client_state.rs

For compatibility with APIs used in other places, change encode_to_vec method defined via any_convert macro to return a Result.  The method is still infallible and the error type reflects that but it’s now valid to run `foo.encode_to_vec().unwrap()`.  To not deal with the error case, `encode` method is provided in addition.

cf-guest: change encode_to_vec to return Result

---

common/cf-guest/src/client_impls.rs
solana/solana-ibc/programs/solana-ibc/src/client_state.rs
solana/solana-ibc/programs/solana-ibc/src/validation_context.rs

Updating revision number of height to 1 from 0 since while decoding, the revision number field which is omitted while encoding ( since its 0 ) fails when decoding because of missing field. It could be fixed by having a default value in case of missing field but since it would require upgrading of cosmos node, we can just use revision number as 1.

solana-ibc: update revision number of height to 1

---

common/cf-guest/src/client.rs

Add a method to create a new guest `ClientState` since it has `PhantomData` as private field. It would be used by the relayer generally to form new clientState

cf-guest: add method to create new guest client state

---

common/guestchain/src/manager.rs
solana/solana-ibc/programs/solana-ibc/src/chain.rs

Storing previous consensus states upto a maximum of 20 where the host consensus state can be queried at a particular height. We are storing 20 for the time being but we can go upto 40 or 50 max so that we dont consume a lot of compute units since for `ConnectionOpenAck` takes almost 1.3M CU out of 1.4M.
We need this because the proof height may not always be same as the current height.

solana-ibc: store previous host consensus states

---

Cargo.lock
solana/solana-ibc/programs/solana-ibc/Cargo.toml
solana/solana-ibc/programs/solana-ibc/src/execution_context.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs

We used to store hash of the borsh encoded value in the trie but IBC encodes the value in protobuf and checks the proof against it. So encoding the value as protobuf so that we match the value which IBC expects.

solana-ibc: store protobuf encoded value in trie

---

common/cf-guest/src/client_impls.rs
common/cf-guest/src/lib.rs
common/cf-guest/src/message.rs
common/cf-guest/src/proto.rs
solana/solana-ibc/programs/solana-ibc/src/client_state.rs
solana/solana-ibc/programs/solana-ibc/src/consensus_state.rs

To make it easier to convert to and from Any types which come from other crates than cf-guest depends on, provide AnyConvert trait with to_any and try_from_any methods which perform conversion between given type and Any message without relying on specific Any type.
Secondly, since IBC uses type URLs without domain in Any messages, do the same in our code base.  Firstly, change code converting from Any such that it ignores the domain in the type_url¹.  Secondly, replace TYPE_URL constant with IBC_TYPE_URL constant which excludes the domain.  And lastly, use that constant for GUEST_TYPE in AnyClientState and AnyConsensusState.
This new code will produce different Any representation for types. Though it will be capable of decoding old Any representations.
¹ This is in fact the correct …

cf-guest: provide explicit Any conversion methods and update type URLs

---

solana/solana-ibc/programs/solana-ibc/src/transfer/mod.rs

Using a default value for `memo` inside `packet` so that if field is not found, we use the default value which is an empty string.

solana-ibc: use serde default for memo to use default value when field is not found

---

Cargo.lock
Cargo.toml
solana/solana-ibc/programs/solana-ibc/src/transfer/mod.rs

Using the fork to box the headers of misbehavior since they can get pretty large on the stack. Also for converting the TM headers from Any, using the decode header defined until ibc-rs 0.48.2 which uses internally defined error rather than calling Protobuf and formatting errors using string which seems to be taking a bit more stack than the latter causing it to overflow on the contract.

solana-ibc: use forked ibc which `boxes` header in misbehaviour and uses less stack when decoding tm header.

---

solana/solana-ibc/programs/solana-ibc/src/lib.rs

The storage and instruction accounts in Chain passed to generate_block aren’t actually used.  Remove them.

solana-ibc: remove unused accounts in Chain

---

Cargo.lock
common/cf-guest/src/proof.rs
common/sealable-trie/src/lib.rs
common/sealable-trie/src/nodes.rs
common/sealable-trie/src/trie.rs
common/sealable-trie/src/trie/del.rs
common/sealable-trie/src/trie/iter.rs
common/sealable-trie/src/trie/seal.rs
common/sealable-trie/src/trie/set.rs
solana/trie/Cargo.toml
solana/trie/src/alloc.rs

Take advantage of niche values of RawNode to mark nodes which has not yet been allocated or have been freed.  This allows the code to detect double-free errors.

solana-trie: add double-free detection

---

common/cf-guest/src/lib.rs
common/guestchain/src/ibc_state.rs

Through the magic of copy’n’paste, the typo of ‘bond’ rather than ‘bound’ spread to multiplle places.  Fix all of that.

Tiny typo fix; s/bond/bound/

---

common/cf-guest/src/client/impls.rs
common/cf-guest/src/client/tests.rs
common/cf-guest/src/proof.rs
common/guestchain/src/validators.rs
solana/signature-verifier/src/ed25519.rs

To help usage of cf-guest with old IBC versions, provide more APIs
which don’t depend on IBC types.  For example, rather than taking
CommitmentRoot simply take byte slice.

cf-guest: provide more IBC-independent interfaces

---

Cargo.lock
solana/trie/Cargo.toml
solana/trie/src/alloc.rs
solana/trie/src/header.rs
solana/trie/src/lib.rs

There are two changes to the format.  They are backwards-incompatible.
Firstly, add more padding to the header so that it is 72 bytes.  This
way the header has the same size as allocated blocks and indexes at
which blocks are stored are aligned to their size.  Secondly, change
the Ptr value from being byte offset to block index.  I.e. rather than
offset 72 or 144 the Ptr is now 1 or 2.
There are two motivating factors for this change.
Firstly, this change makes Ptr space more ‘dense’.  With Solana
account being at most 10 MiB, the highest Ptr value fits in 18 bits.
Ptr is limited to 30 bits so that leaves 12 bits for further
extensions.  For example, if we ever need to split the trie into
multiple accounts, those bits could be used to store 4-bit account
index and 8-bit bump value. …

solana-trie: change header and pointer format 

---

solana/restaking/tests/restaking.ts

In some cases, when we check for failure case in restaking tests, we would want to fail the test if the callback passes. But before we use to throw the error in try which was getting ignored in catch. So now, we are throwing the error outside the try if the callback inside passes.

proper exception handling in restaking tests

---

solana/solana-ibc/programs/solana-ibc/src/client_state/impls.rs

Tendermint verifier has a generic which gives us ability to choose a type to implement custom hash logic. Since the default `sha256` hashing takes a lot of compute units, we need to use sha256 from solana syscalls which use significantly low compute units.

solana-ibc: use custom hash for tm sig verification

---

solana-test.sh
solana/solana-ibc/programs/solana-ibc/src/chain.rs
solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/tests.rs

Fetch signatures from signature account which has all the signatures added in the `sigverify` program. Since a transaction can only contain 1232 bytes, we need to chunk these signatures, store them in an account and fetch them in the `deliver` method. The chunking and adding them to the account is done in `sigverify` program and we just extract those signatures from the account provided as `remaining_accounts` since its only required when `UpdateClient` message is sent.

solana-ibc: fetch signatures from signatures account 

---

solana/solana-ibc/programs/solana-ibc/src/lib.rs

There might be some instances where we need client state at a particular height mostly for finding the proof height of a packet. But since we are only storing the latest client state and storing previous states is expensive, we can just log it and fetch it whenever we want by traversing the previous logs. The height is also logged to find the proof height which is `height + 1`. Though it might not be used as much, but its logged for convenience.

solana-ibc: log client state and current block height

---

Cargo.lock
Cargo.toml
solana/solana-ibc/programs/solana-ibc/Cargo.toml
solana/solana-ibc/programs/solana-ibc/src/client_state/impls.rs
solana/solana-ibc/programs/solana-ibc/src/ibc.rs

Take advantage of new features of ibc-rs which allow passing HostFunctionsProvider and SHA256 implementation to Tendermint code.
So far, IBC would hard-code native implementation whereas what we want is calls to Solana syscalls.  With recent changes to ibc-rs it’s now possible for us to pass our own implementation for the hash calculation.

solana-ibc: provide hash implementations to Tendermint code

---

common/stdx/src/lib.rs
solana/signature-verifier/src/api.rs
solana/signature-verifier/src/ed25519_program.rs
solana/signature-verifier/src/program.rs
solana/signature-verifier/src/verifier.rs

Change sigverify program so that whenever new entries are add, they are sorted.  While this makes adding signatures more expensive, this helps when checking signatures since a logarithmic search can be used rather than linear scan of the account.

sigverify: sort entries to speed up lookup

---

.gitignore
Cargo.lock
Cargo.toml
validator/Cargo.toml
validator/src/command.rs
validator/src/stake.rs
validator/src/utils.rs
validator/src/validator.rs

The new validator client has the following improvements.
- not use spinner to send the transaction since it takes forever.
- use program id from config for deriving PDA and calling the program.
- check if pending block exists else create a new block.
- sign only if the current block is unsigned.
- add priority fees as config to let users choose their custom fee.
- submit tx to jito client instead of rpc.
- remove custom accounts structure for staking.

validator: Improve validator client

---

Cargo.lock
Cargo.toml
common/cf-guest/Cargo.toml
common/cf-guest/src/client/impls.rs
solana/solana-ibc/programs/solana-ibc/Cargo.toml
solana/solana-ibc/programs/solana-ibc/src/client_state/impls.rs

Since we have added new methods to the Validation and Execution traits in ibc, we need to implement those. The traits are added to reuse the headers instead of deserializing every time since they consume a lot of units.

solana-ibc: implement missing traits from ibc

---

Cargo.lock

This probably doesn’t affect us but in any case, update h2 dependency to address a potential DoS vulnerability.
See https://seanmonstar.com/blog/hyper-http2-continuation-flood/.

Update h2 dependency to address potential DoS

---

solana/restaking/programs/restaking/src/lib.rs
solana/restaking/programs/restaking/src/validation.rs
solana/restaking/tests/instructions.ts
solana/solana-ibc/programs/solana-ibc/src/lib.rs

The Instructions sysvar isn’t used directly by the restaking contract and instead is passed via CPI to the solana-ibc contract.  As such, it’s safe to not verify the account since solana-ibc will perform the verification.  Nonetheless, to introduce another layer of protection, check that the passed account is what we expect.
Note: In addition, remove instruction account from WithdrawalRequest call since it was never used.

restaking: add checking for the Instructions sysvar

---

validator/src/stake.rs

We were sending transaction for staking through jito which is a bit immature since it doesnt return an error when it fails. So switching it back to send it through rpc.

validator: remove jito mev client for staking

---

solana/solana-ibc/programs/solana-ibc/src/lib.rs

Log the height in send transfer method similar to what we do in `deliver` method.

solana-ibc: log current height in send transfer method

---

solana/solana-ibc/programs/solana-ibc/src/error.rs
solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/tests.rs

When a packet is being sent, the timeout height and timeout timestamp can both be set to zero which effectively means that the packet can never time out. And there is no explicit check to prevent this. And this packet would never be accepted by cosmos since cosmos has a check that skips the packet if both the timeouts are zero. And since the packet never times out, the funds would be stuck forever.

solana-ibc: Check atleast one of the timeouts are non zero.

---

solana/solana-ibc/programs/solana-ibc/src/client_state.rs

Pruning all expired consensus states may take quite a while to the point when the solana-ibc contract runs out of compute units.
Unfortunately, Tendermint light client doesn’t have an obvious way to limit how many states are inspected and deleted.  Instead, we hack the consensus_state_heights method so that it reports only the earliest height.
With this change, Tendermint light client will only consider a single state for deletion.

solana-ibc: delete only one Tendermint consensus state at a time

---

common/cf-guest/src/client/impls.rs
common/cf-guest/src/client/tests.rs
solana/solana-ibc/programs/solana-ibc/src/client_state.rs

Pruning all expired consensus states may take quite a while to the point when the solana-ibc contract runs out of compute units. Instead, change the code so only the earliest consensus state is checked and pruned.

cf-guest: delete only one consensus state at a time

---

solana/solana-ibc/programs/solana-ibc/src/validation_context.rs

Update block time from 1 second to 3600 second which is used to estimate the delay from the timestamp. It refers to the maximum block time and not the average block time.

solana-ibc: Update block time

---

Cargo.lock
Cargo.toml

Update tendermint dependency to include our sign bytes reuse code.
The fork is mostly Tendermint 0.36.0 with just the sign bytes encoding
optimisation.

Update tendermint dependency

---

solana/solana-ibc/programs/solana-ibc/src/client_state.rs
solana/solana-ibc/programs/solana-ibc/src/events.rs
solana/solana-ibc/programs/solana-ibc/src/execution_context.rs

As per comment, perhaps it’s better to use proper event? This PR does three things:
- Converts the behaviour from logging to emitting an event.
- Adds an event for consensus state.  I honestly don’t know how useful that is? If we don’t need it it might be better to skip it.
- Changes to output proto encoding rather then borsh. This is because proto is what is being hashed and stored in the trie, so perhaps that’s more convenient than outputting borsh?
Thoughts?

convert to events and add event for consensus

---

common/cf-guest/src/client/impls.rs
common/cf-guest/src/proof.rs

Packet commitments, receipts and acks are stored in the trie as is rather than being hashed.  This is because they are already 32-byte hashes and there is no need to hash that again.
However, the membership proof verification didn’t take that into account and hashed the commitments checking if the hash exists in the trie.
Fix the implementation so that the commitment value is taken raw and checked that it exists in the trie.

cf-guest: fix commitment membership proofs verification

---

solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs
solana/solana-ibc/programs/solana-ibc/src/tests.rs
solana/solana-ibc/programs/solana-ibc/src/transfer/mod.rs

Make fees configurable by storing them in the private storage account instead of hard-coding them in the source code.

solana-ibc: make fees configurable by the fee collector

---

common/guestchain/src/candidates.rs
common/guestchain/src/candidates/tests.rs
common/guestchain/src/manager.rs
solana/solana-ibc/programs/solana-ibc/src/chain.rs

Change the ChainManager::update_candidate such that rather than the new stake it takes a callback function that returns the new stake. This allows modifications to be implemented without having to look up the candidate twice (once to read existing value an the other time to set the new value).

guestchain: change ChainManager::update_candidate to take a callback

---

solana/solana-ibc/programs/solana-ibc/src/chain.rs
solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/tests.rs

To be honest, I’d rather the staking program address was configurable at run time but in interest of time and code simplicity, hard code it in the source of solana-ibc.

solana-ibc: hard code staking program address

---

common/guestchain/src/manager.rs
solana/solana-ibc/programs/solana-ibc/src/chain.rs

Nothing uses force argument of ChainManager::generate_next so to simplify code get rid of it.

guestchain: remove force argument from ChainManager::generate_next

---

solana/solana-ibc/programs/solana-ibc/src/lib.rs

Checking if the CPI call is being made from one of the multiple program ids since there can be multiple staking programs which can update the stake.

solana-ibc: Add multiple staking program ids

---

.gitignore
.vscode/settings.json
solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/tests.rs
solana/solana-ibc/programs/solana-ibc/src/transfer/impls.rs

Whenever someone sends SOL to Solana, they get wrapped sol instead of native SOL which is unusable if the wallet didnt have SOL previously. So whenever someone send SOL from solana, the escrow account which holds wsol gets closed and all the lamports are sent to the `mint_authority` account which is the owner of the escrow account. When we unescrow the wrapped sol, we debit it from the `mint_authority` account instead of transferring from the `escrow` account. This will allow users to receive native SOL on solana instead of wrapped sol. Though when users deposit, they need to have wrapped SOL which can be a prior instruction to convert SOL to wSOL.

solana-ibc: Unwrap sol when unescrowing wrapped sol.

---

solana/solana-ibc/programs/solana-ibc/src/error.rs
solana/solana-ibc/programs/solana-ibc/src/lib.rs

Adding a method which would enable us to change the connection delay period of a specified connection end. This method can only be called by `fee_collector` and would fail if a `connection_id` that doesnt exist is passed.

solana-ibc: method to update connection delay of specified connection id

---

solana/solana-ibc/programs/solana-ibc/src/transfer/impls.rs

the rent for the wrapped sol escrow token account which is closed should be calculated from rent object based on the lenght of account data.

solana-ibc: get rent from account data size

---

solana/solana-ibc/programs/solana-ibc/src/lib.rs

Some of the accounts are marked as `mut` but they are never written so removing it which can improve the performance.

solana-ibc: remove unneccesary writable for accounts.

---

.github/workflows/master.yml
Cargo.lock
Cargo.toml

Unfortunately, Rust 1.80 breaks `time` dependency.  Specifically,
a build fails with the following error:
error[E0282]: type annotations needed for `Box<_>`
--> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.30/src/format_description/parse/mod.rs:83:9
|
83 |     let items = format_items
|         ^^^^^
...
86 |     Ok(items.into())
|              ---- type must be known at this point
This shouldn’t be a problem since we can update the dependency.
Unfortunately, when we install Anchor CLI, that still uses old `time`
crate and build of that fails.
For the time being, pin the compiler version in CI to 1.80 to avoid
this build failure.
This commit also updates `time` dependency in case our code is built
with newest Rust.

Pin Rust version in CI to avoid time build failures

---

Cargo.lock
Cargo.toml

We are stuck at using Rust version that Anchor CLI is using (which is not the latest release).  Sadly, serde 1.0.204 requires a new version which stabilises `diagnostic` attribute name space.  Pin serde to last supported version so that code builds with Rust we’re using.

Pin serde to 1.0.203 to avoid build failure with newer version

---

solana/restaking/programs/restaking/src/lib.rs

When depositing, the stake is updated by fetching the stake from `validator` and appending the new value. But during withdrawal, the stake is updated by fetching from `candidate` which creates mismatch between the value. So updating the stake using the `candidate` for all the instances.

restaking: fetch the stake from candidate instead of validator

---

common/cf-solana/src/proof.rs
common/cf-solana/src/proof/tests.rs
common/cf-solana/src/types.rs
common/cf-solana/src/utils.rs

Firstly, add DeltaHashProof type which contains all the information that are needed to calculate delta hash.  One piece of information in it is the accounts delta hash.  As such, this struct together with a trusted bank hash acts as a proof for the accounts delta hash.
Secondly, create AccountHashData wrapper for the account_hash_data field of the AccountProof struct.  This improves type safety and better encapsulates the account information used in hash calculation.
Lastly, fix a few instances where solana-program2 Cargo feature name was used instead of proper solana-program-2.

cf-solana: add bank hash handling plus some refactoring

---

Cargo.lock
validator/Cargo.toml
validator/src/validator.rs

When checking if block can be generated, it looks for whether the block age is more than minimum or if there is change in the state. But the timestamp used to check the age is in nanoseconds and hence the timestamp should be provided in nanoseconds.

validator: use timestamp in ns while checking if block can be generated

---

common/cf-guest/src/client/impls.rs
common/cf-guest/src/proof.rs

Introduce proof::generate_for_trie and proof::verify_for_trie functions which generate and verify proofs where state root is the trie root hash. Those proofs don’t include the guest block header at the front of the proof.  The first user of them is the rollup light client since there is no guest blockchain running on the rollup.
For consistency, rename proof::generate to proof::generate_for_block and proof::verify to proof::verify_for_block.

cf-guest: add support for proofs without block header

---

solana/trie-geyser/Cargo.lock
solana/trie-geyser/Cargo.toml

trie-geyser doesn’t directly use Rayon.  Remove it from dependencies and instead enable the feature in cf-solana which (optionally) uses it.

trie-geyser: fix use of Rayon

---

solana-test.sh
solana/bridge-escrow/programs/bridge-escrow/src/lib.rs
solana/bridge-escrow/programs/bridge-escrow/src/tests.rs

For cross domain transfers, an acknowledgement is sent from destination to source in form of a token transfer. The packet contains the memo that has the information about unlocking the funds. The source would then parse the memo and unlock the funds to the solver mentioned in the memo. Since we only have token transfers enabled and no cross chain messages, a token needs to be transferred. For this, we create a dummy token owned by the program which mints a token everytime and sends a transfer. The timeout of the transfer is set to infinite so that it always reaches the counterparty chain.
Also the `on_receive_transfer` method accepts a memo which unlocks the funds to the solver. Right now it is being called by the auctioneer but once the hooks are enabled on `solana-ibc` program, this …

fast-bridge: Send required accounts for cross domain transfer

---

solana/bridge-escrow/programs/bridge-escrow/src/bridge.rs
solana/bridge-escrow/programs/bridge-escrow/src/lib.rs
solana/bridge-escrow/programs/bridge-escrow/src/tests.rs

If the solver is not able to solve the intent, then the escrowed funds can be issued back to the user. In case of single domain intents, the funds just get transferred to the user from the escrow account. But for cross chain intents, a timeout message is sent to the other chain with a flag of `Timeout` and the user who should receive it. 
The intent should store the user on source chain so that during timeout, we know whom to refund the funds to. For the memo, it is the same format and only the receiver is changed to user address instead of solver.

fast-bridge: Timeouts

---

solana/solana-ibc/programs/solana-ibc/src/lib.rs

When inner CPI calls are being made, the called program can only know the initial program which made the CPI. It cannot know if there were inner CPI calls being made before calling the last one. So to whitelist the `update_stake` method, it should check if the caller is bridge-contract program ID instead of restaking program ID since its the bridge contract that would call the restaking and then the solana-ibc.

solana-ibc: replace restaking staking program id with bridge contract program id

---

common/cf-solana/src/proof.rs
common/guestchain/src/manager.rs

The Candidates struct has a changed flag indicating whether the set of candidates has changed (in such a way that it would affect the validators set).  This is used to determine whether a new epoch should be started or not.  Once next epoch is scheduled in the block, the flag should be cleared.
Alas, the code clears the flag each time block is generated even if a new epoch isn’t about to start.  As a consequence, if set of candidates changes in the middle of an epoch, the change will not be reflected once the new epoch is ready to start.
Fix this by clearing the flag only if next_epoch is populated in produced block.

guestchain: clear candidates changed flag only if new epoch to start

---

solana/solana-ibc/programs/solana-ibc/src/storage.rs
solana/trie/src/lib.rs
solana/trie/src/witness.rs
validator/src/validator.rs

Allow customising TrieAccount through a generic witness type.  The main use case is making it TrieAccount Send and Sync by removing support for the witness.  This is needed by, for example, relayer.

solana-trie: make witness generic type

---

Cargo.lock
Cargo.toml
solana/trie-geyser-plugin/Cargo.lock

borsh 0.10.3 is vulnerable to RUSTSEC-2023-0033.  While this doesn’t directly affect us, update the dependency so we’re not even subject to this theoretical issue.

Update borsh dependency to address RUSTSEC-2023-0033 vulnerability

---

solana/solana-ibc/programs/solana-ibc/src/client_state.rs
solana/solana-ibc/programs/solana-ibc/src/client_state/impls.rs
solana/solana-ibc/programs/solana-ibc/src/consensus_state.rs

Adding guest client and consensus states so that the solana-ibc on the rollup can store them. The guest client and consensus state was previous removed since we used to store the wasm wrapped guest states. It was removed here https://github.com/ComposableFi/emulated-light-client/pull/255 and now its added again.

solana-ibc: add guest client and consensus states

---

common/cf-guest/src/client/impls.rs
common/cf-solana/src/client/impls.rs

This is to increase compatibility with other libraries which fail to
properly decode proto3 message with missing revision number field
(missing fields should be decoded as zero in proto3).

light-clients: update revision number for cf-guest and cf-solana to 1

---

common/cf-guest/src/client/impls.rs
common/cf-solana/src/client/impls.rs

If the client state is not found when finding the status, it means that a new client is getting created in which case, we should return the status as active unless the client state is already frozen ( which is checked before ).

solana-ibc: return status as active if client state not found

---

common/memory/src/lib.rs
common/sealable-trie/src/bits.rs
common/sealable-trie/src/bits/ext_key.rs
common/sealable-trie/src/trie/tests.rs
common/trie-geyser/src/api.rs
solana/signature-verifier/src/api.rs
solana/solana-ibc/programs/solana-ibc/src/client_state.rs
solana/solana-ibc/programs/solana-ibc/src/client_state/impls.rs
solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/tests.rs

Mostly address `cargo clippy --fix` with some other minor
modifications.  The biggest refactoring is `host_metadata` method in
`client_state.rs` (but of course no behaviour changes).

Various minor clippy fixes

---

common/cf-solana/src/client/impls.rs

in the `consensus_has_expired` method, the consensus timestamp is fetched in seconds but added to a trusting period which is in nanoseconds creating a mismatch. So fixing this bug by fetching the consensus timestamp in nanoseconds.

cf-solana: get timestamp in ns for cf-solana

---

common/cf-guest/src/client/impls.rs
common/cf-solana/src/client/impls.rs

Since prefix is expected to be empty, send empty prefixes when verifying proofs.

light-clients: make prefix empty for both cf-solana and cf-guest

---

solana/solana-ibc/programs/solana-ibc/src/lib.rs

When establishing the connection, we need to store the consensus state on chain before the client is stored since the consensus state would be required during `OpenTry` or `OpenAck` based on order of how the connection is established. So storing the consensus state during `initialize` method so that when the client is created, it can use the stored consensus state.

witness: store local consensus state during initialization for witness feature

---

solana/solana-ibc/programs/solana-ibc/src/lib.rs

Fix the condition to check if the connection id index is more than the number of conditions.

solana-ibc: fix condition to check connection id

---

solana/restaking/programs/restaking/Cargo.toml
solana/solana-ibc/programs/solana-ibc/src/validation_context.rs

Host consensus state is required for establishing the connection. So the host consensus state should be returned based on whether the `witness` feature is present or not. If the feature is present, then we return the rollup consensus state else we return the guest consensus state. But the issue is if the `witness` feature is not enabled, it could either be guest or wasm ( which is a wrapper version of guest ). Since the connection with cosmos is already established, we would stick to returning the `guest` consensus state for now.

solana-ibc: get host consensus state based on feature

---

Cargo.lock
solana/solana-ibc/programs/solana-ibc/Cargo.toml
solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/storage.rs
solana/solana-ibc/programs/solana-ibc/src/transfer/mod.rs

A message is sent through IBC to unlock the funds of the solver. To achieve this, the solana-ibc program needs to forward the memo to the `bridge-escrow` program so that it can release the funds to the solver. Since anybody can send memo, we execute the hook only if the transferred token is the token owned by the `bridge-escrow` on the counterparty chain (ethereum). This allows us to verify that the message to unlock the funds originated from the right contract and it is not spoofed.

IBC Hooks: add hooks to call bridge escrow program

---

solana/solana-ibc/programs/solana-ibc/src/transfer/mod.rs

Since PFM only support passing of the memo for the next transfer as json, strings can be passed. So we have to deserialize the memo with json and get the string from it. Also log the acknowledgement after the hooks is performed since the ack can change based on the result of hooks.

hooks: fix hook structure by deserializing json instead of string

---

Cargo.lock
bridge-escrow-test.sh
solana/bridge-escrow/programs/bridge-escrow/src/lib.rs
solana/bridge-escrow/programs/bridge-escrow/src/tests.rs

To run a test, you can simply execute the following command.
```sh
./bridge-escrow-test.sh
```
- send_funds_to_user 
- send_funds_to_user_cross_chain 
- escrow_and_store_intent 
- Added the test for `send_funds_to_user `
- Still needs to add some assertions.
- `bridge::bridge_transfer` seems to be updated. But needs help of @Alberto

update: fix issues in native sol transfer

---

.github/workflows/master.yml
solana/solana-ibc/programs/solana-ibc/src/lib.rs
solana/solana-ibc/programs/solana-ibc/src/transfer/mod.rs

Check if the accounts passing to the program through the hook is initialized. If any of them is not initialized, then the hook program would not be called and a failed acknowledgement would be sent back.

ibc-hook: Add validation for hooks

---

.github/workflows/master.yml
Cargo.lock
Cargo.toml

Update the revision of ibc-rs so that the client cannot be expired since there is no way of reviving the client in ibc-rs version of 0.50.0. Once the ibc-rs is updated to the latest version, this wont be required.
rev: https://github.com/mina86/ibc-rs/commit/87ebc7d20c3ed955d2c70c0845c88dcb3b574a80

update the revision of ibc-rs
