ComposableFi/emulated-light-client

solana/solana-ibc/programs/solana-ibc/src/lib.rs, solana/solana-ibc/programs/solana-ibc/src/tests.rs
Instead of creating an any wrapper for possible deliver messages, pass
the MsgEnvelope directly and encode it with borsh.
=> solana-ibc: don’t wrap deliver messages in protobuf message

solana/solana-ibc/programs/solana-ibc/src/lib.rs, solana/solana-ibc/programs/solana-ibc/src/storage.rs
Extract code which creates AccountTrie from the AccountInfo to
a separate function so that it can be easily reused.  Furthermore, add
ownership checks which so far were missing.
Long term I’d like to have a wrapper which can be used inside of
Accounts struct but I couldn’t quite figure out the proper way to
implement it.  AccountTrie isn’t quite zero copy (since it makes copy
of the header data).  This is left for future improvement.
=> solana-ibc: add function for checking the Trie account

Cargo.toml, solana/solana-ibc/programs/solana-ibc/src/client_state.rs, solana/solana-ibc/programs/solana-ibc/src/consensus_state.rs, solana/solana-ibc/programs/solana-ibc/src/execution_context.rs, solana/solana-ibc/programs/solana-ibc/src/lib.rs, solana/solana-ibc/programs/solana-ibc/src/storage.rs, solana/solana-ibc/programs/solana-ibc/src/validation_context.rs
Closes: https://github.com/ComposableFi/emulated-light-client/issues/46
=> solana-ibc: use Borsh for consensus state serialisation

Cargo.toml
Bumping anchor to latest version.
=> bumped anchor to 0.29

solana/solana-ibc/programs/solana-ibc/src/tests.rs
Since we are using optional accounts, there is no need for us to have
structures regarding the remaining accounts in the tests.
=> solana-ibc: removed remaining accounts from tests

solana/restaking/README.md, solana/restaking/tests/restaking.ts
Updating readme to add about rewards, receipt token, oracles and other instructions. Adding needful docs in the tests file.
=> restaking: update Readme and docs in TS tests

solana/restaking/querying.md
Instructions on the data and how it can be queried using solana rpc in typescript on client side.
=> restaking: added instructions on how contract can be queried

solana/restaking/README.md
updating restaking readme to refer to composable docs for receipt tokens instead of google doc.
=> restaking: Update restaking Readme

solana/solana-ibc/programs/solana-ibc/src/tests.rs, solana/write-account/src/instruction.rs, solana/write-account/src/program.rs
Introduce Free operation to the write-account program which allows the
Write account to be freed and all lamports stored within it
transferred back to the Payer.
=> write-account: add Free operation

validator/src/validator.rs
Moving pending block outside the loop since its needed only for restarts. Validator would then listen to events and sign the block without needing to access the data from the smart contract making it independent of the changes that would be done on the contract.
=> validator: move pending block signing outside the loop

common/sealable-trie/src/bits.rs
Owned::pop_back breaks the invariant of bytes being empty if length is zero when poping last bit from a slice with non-zero offset.  Fix that by poppping the last byte from the vector if length becomes zero.
=> sealable-trie: fix length invariant breaking in Owned::pop_back

solana/restaking/tests/instructions.ts, solana/restaking/tests/restaking.ts
Add `set_service` instruction that can be used in FE.
=> restaking: set service instruction

solana/solana-ibc/programs/solana-ibc/src/allocator.rs
Reduce amount of unsafe code by replacing a raw pointer with a reference wrapped inside of an Option.
=> solana-ibc: prefer optional reference to raw pointers

solana/solana-ibc/programs/solana-ibc/src/allocator.rs
None of the unit tests refer to functions relying on the mutable global state defined in the allocator module.  Similarly, none of the interfaces exposed to reverse-dependencies (to facilitate CPI) use it either.
Simplify global mutable state handling by removing support for it from non-Solana smart contract builds.
=> solana-ibc: remove global state support from non-Solana builds

common/sealable-trie/src/nodes.rs, common/sealable-trie/src/trie.rs, common/sealable-trie/src/trie/set.rs, solana/restaking/programs/restaking/src/lib.rs, solana/restaking/tests/instructions.ts, solana/solana-ibc/programs/solana-ibc/src/lib.rs, solana/solana-ibc/programs/solana-ibc/src/tests.rs
Each finding is a small change so sending all this as a single PR.  For review I recommend looking at each individual commit rather than full PR. I’m going to marge it as a rebase so this will show up nicely in history as well.
=> Address various audit findings

Anchor.toml, solana/solana-ibc/programs/solana-ibc/src/error.rs, solana/solana-ibc/programs/solana-ibc/src/lib.rs, solana/solana-ibc/programs/solana-ibc/src/storage.rs, solana/solana-ibc/programs/solana-ibc/src/tests.rs, solana/solana-ibc/programs/solana-ibc/src/transfer/mod.rs
**Charging fees**
On send_transfer:
- At the beginning of the function, take the fee
**Refunding fees**
On timeout:
- if the timeout is properly processed upon execution -> refund
On acknowledgement
- if there was an error on the counterparty chain -> refund fees
=> solana-ibc: fee processing

Cargo.toml
Update the version of overall project and the authors.
=> update version and author

solana/solana-ibc/programs/solana-ibc/src/lib.rs, solana/solana-ibc/programs/solana-ibc/src/tests.rs
Removing send packet method for now since we dont support cross chain messaging yet.
=> solana-ibc: remove send packet method

Cargo.toml
Updating the version of program to 0.0.2 to sync with releases.
=> solana-ibc update version of program

Cargo.lock, Cargo.toml, solana/allocator/Cargo.toml, solana/restaking/programs/restaking/Cargo.toml, solana/signature-verifier/Cargo.toml, solana/solana-ibc/programs/solana-ibc/Cargo.toml, solana/trie-example/Cargo.toml, solana/trie/Cargo.toml, solana/write-account/Cargo.toml
Using version from workspace for all the programs inside `solana` folder.
=> use version from workspace

Cargo.lock, common/cf-solana/Cargo.toml, common/cf-solana/src/blake3.rs, common/cf-solana/src/proof.rs, solana/solana-ibc/programs/solana-ibc/Cargo.toml, solana/solana-ibc/programs/solana-ibc/src/client_state.rs, solana/solana-ibc/programs/solana-ibc/src/client_state/impls.rs, solana/solana-ibc/programs/solana-ibc/src/consensus_state.rs
Best reviewed as individual commits. I intend to rebase and and merge rather than squash this PR.
=> solana-ibc: add support for cf-solana light client

solana/solana-ibc/programs/solana-ibc/src/lib.rs, solana/solana-ibc/programs/solana-ibc/src/transfer/mod.rs
Whitelist mantis hook token address so that we execute the hook when its transferred.
=> whitelist mantis hook address
